#!/bin/bash

# Temporarily store uncommited changes
git stash

# Verify correct branch
git checkout develop

# Build new files
ghc --make site.hs
./site clean
./site build

# Get previous files
git fetch --all
git branch -D master
git checkout -b master --track origin/master

# Overwrite existing files with new files
cp -a _site/. .

# Or use Rsync to delete old files
#rsync -a --filter='P _site/' --delete-excluded _site/ .

# Commit
git add -A
git commit -m "$(date '+%Y-%m-%d')"

# Push
git push origin master:master

# Restoration
git checkout develop
git branch -D master
git stash pop
